title: Rauber musik
tagline: Violinateljé i Motala
description: >-
  Violinateljé i Motala. Reparationer och försäljning av stråkinstrument
  och tillbehör, samt nytillverkning av stråkar.
url: https://raubermusik.com
lang: sv-SE

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

# Vi behöver inte den maskinläsbara listan över omdirigeringar.
redirect_from:
  json: false

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - tools
  - vendor
